# Generated by Django 6.0.9 on 2026-10-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='billing_sub_organiz_e1331c_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['organization', 'metric', 'period_start'], name='billing_usa_organiz_512e97_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('organization', 'metric', 'period_start'), name='uniq_usage_org_metric_period'),
        ),
    ]
