# Generated by Django 6.0.9 on 2026-10-08 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('message.received', 'Message Received'), ('message.sent', 'Message Sent'), ('contact.created', 'Contact Created'), ('conversation.created', 'Conversation Created'), ('keyword.detected', 'Keyword Detected'), ('bot.connected', 'Bot Connected'), ('bot.disconnected', 'Bot Disconnected')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft')], db_index=True, default='draft', max_length=16)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('run_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('send_message', 'Send Message'), ('send_template', 'Send Template'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('assign_conversation', 'Assign Conversation'), ('call_webhook', 'Call Webhook'), ('delay', 'Delay')], max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(help_text="Dotted path into the event payload, e.g. 'text'", max_length=128)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('starts_with', 'Starts With'), ('exists', 'Exists')], max_length=16)),
                ('value', models.CharField(blank=True, max_length=512)),
                ('case_insensitive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('log', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
