# Generated by Django 6.0.9 on 2026-10-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('bots', '0001_initial'),
        ('logs', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='bot',
            field=models.ForeignKey(blank=True, help_text='Null = applies to all org bots.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='bots.bot'),
        ),
        migrations.AddField(
            model_name='automation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='automationcondition',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.event'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='automation',
            index=models.Index(fields=['organization', 'trigger_type', 'status'], name='automations_organiz_604c79_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['automation', 'created_at'], name='automations_automat_cdb034_idx'),
        ),
    ]
