# Generated by Django 6.0.9 on 2026-10-08 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.bot')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='uniq_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_session_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('state', models.CharField(choices=[('created', 'Created'), ('connecting', 'Connecting'), ('qr_required', 'Qr Required'), ('authenticated', 'Authenticated'), ('connected', 'Connected'), ('reconnecting', 'Reconnecting'), ('disconnected', 'Disconnected'), ('logged_out', 'Logged Out'), ('error', 'Error')], db_index=True, default='created', max_length=16)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('qr_regeneration_count', models.PositiveIntegerField(default=0)),
                ('qr_window_start', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('reconnect_attempts', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_session', to='bots.bot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_sessions', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='whatsapp_wh_state_091da2_idx')],
            },
        ),
    ]
