# Generated by Django 6.0.9 on 2026-10-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'status'], name='api_keys_ap_organiz_ff1a24_idx'),
        ),
    ]
