# Generated by Django 6.0.9 on 2026-10-08 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('phone_country', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=16)),
                ('connection_status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('qr_required', 'Qr Required'), ('connected', 'Connected'), ('reconnecting', 'Reconnecting'), ('logged_out', 'Logged Out'), ('error', 'Error')], db_index=True, default='disconnected', max_length=16)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='bots_bot_organiz_da1240_idx'), models.Index(fields=['connection_status'], name='bots_bot_connect_a789de_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_bot_org_slug')],
            },
        ),
    ]
